#!/bin/sh
set -eu

: "${CLAUSIS_VERSION:?CLAUSIS_VERSION must be supplied by build-in-container}"
volume_version=$(printf '%s' "$CLAUSIS_VERSION" | tr -d .)

lb config noauto \
  --mode debian \
  --architectures amd64 \
  --distribution stable \
  --archive-areas "main contrib non-free-firmware" \
  --binary-image iso-hybrid \
  --bootappend-live "boot=live components username=clausis hostname=clausis quiet splash clausis.audio_bootstrap=1" \
  --bootloaders "grub-efi,syslinux" \
  --debian-installer none \
  --image-name "clausis-$CLAUSIS_VERSION-amd64" \
  --iso-application "Clausis $CLAUSIS_VERSION" \
  --iso-publisher "Clausis community prototype" \
  --iso-volume "CLAUSIS_$volume_version" \
  --memtest none \
  "${@}"
