#!/bin/sh
set -eu

lb config noauto \
  --mode debian \
  --architectures amd64 \
  --distribution stable \
  --archive-areas "main contrib non-free-firmware" \
  --binary-image iso-hybrid \
  --bootappend-live "boot=live components username=clausis hostname=clausis quiet splash clausis.audio_bootstrap=1" \
  --bootloaders "grub-efi,syslinux" \
  --debian-installer none \
  --image-name clausis-0.1.2-amd64 \
  --iso-application "Clausis 0.1.2" \
  --iso-publisher "Clausis community prototype" \
  --iso-volume "CLAUSIS_012" \
  --memtest none \
  "${@}"
