#!/bin/sh
set -eu

lb config noauto \
  --mode debian \
  --architectures amd64 \
  --distribution stable \
  --archive-areas "main contrib non-free-firmware" \
  --binary-image iso-hybrid \
  --bootappend-live "boot=live components username=voiceos hostname=voiceos quiet splash voiceos.audio_bootstrap=1" \
  --bootloaders "grub-efi,syslinux" \
  --debian-installer none \
  --image-name voiceos-0.1.0-amd64 \
  --iso-application "VoiceOS 0.1.0" \
  --iso-publisher "VoiceOS community prototype" \
  --iso-volume "VOICEOS_010" \
  --memtest none \
  "${@}"
