---
dontChroot: true
timeout: 300
verbose: false
script:
  - command: "/usr/libexec/calamares-clausis/calamares_clausis.py --guard-transaction --device '${gs[clausisSelectedDevice]}' --install-mode '${gs[clausisInstallMode]}' --encrypted '${gs[clausisEncryptionEnabled]}' --filesystem '${gs[clausisFilesystem]}'"
    timeout: 300
i18n:
  name: "Bind the selected Clausis installation target"
  name[de]: "Gewählten Clausis-Zieldatenträger sicher binden"
