---
dontChroot: true
timeout: 30
verbose: false
script:
  - command: "/usr/bin/clausis-finalize-hermes-install --root '${ROOT}' --user '${USER}'"
    timeout: 30
i18n:
  name: "Install Clausis Hermes configuration"
  name[de]: "Clausis-Hermes-Konfiguration installieren"
